"""empty message

Revision ID: 3845b5f89aa3
Revises: 9e8c80303d37
Create Date: 2025-04-25 18:59:27.007579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3845b5f89aa3'
down_revision = '9e8c80303d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('away_team_score')
        batch_op.drop_column('home_team_score')

    # ### end Alembic commands ###
