"""Add followers

Revision ID: 51c898e45023
Revises: 64dd36442cfa
Create Date: 2026-03-26 21:59:14.952491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c898e45023'
down_revision = '64dd36442cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('playoff_games')
    op.drop_table('playoff_teams')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('division')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.VARCHAR(length=8), autoincrement=False, nullable=True))

    op.create_table('playoff_teams',
    sa.Column('id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('division_seed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_seed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['teams.id'], name=op.f('playoff_teams_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playoff_teams_pkey'))
    )
    op.create_table('playoff_games',
    sa.Column('id', sa.VARCHAR(length=18), autoincrement=False, nullable=False),
    sa.Column('game_title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['games.id'], name=op.f('playoff_games_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playoff_games_pkey'))
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
