"""empty message

Revision ID: 9e8c80303d37
Revises: 6c6a044cf607
Create Date: 2025-04-25 18:52:01.982767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8c80303d37'
down_revision = '6c6a044cf607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('team_city', sa.String(length=30), nullable=False),
    sa.Column('team_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('home_team_id', sa.String(length=30), nullable=True),
    sa.Column('away_team_id', sa.String(length=30), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('streaming_url', sa.String(length=256), nullable=False),
    sa.Column('has_roster_report', sa.Boolean(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('start_timezone', sa.String(length=8), nullable=True),
    sa.Column('start_time_tbd', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.String(length=18), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    op.drop_table('games')
    op.drop_table('teams')
    # ### end Alembic commands ###
