"""playoff-start

Revision ID: a871c7986cff
Revises: 3845b5f89aa3
Create Date: 2025-07-25 21:20:52.584687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a871c7986cff'
down_revision = '3845b5f89aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_teams',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('division_seed', sa.Integer(), nullable=False),
    sa.Column('overall_seed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_game', ['user_id', 'game_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(length=8), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_index('ix_users_email', [sa.literal_column('lower(email)')], unique=True)
        batch_op.create_index('ix_users_username', [sa.literal_column('lower(username)')], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.drop_index('ix_users_email')
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('division')

    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_game', type_='unique')

    op.drop_table('playoff_teams')
    # ### end Alembic commands ###
