"""playoff-games

Revision ID: e178e02c47c5
Revises: a871c7986cff
Create Date: 2025-07-25 21:33:20.043501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e178e02c47c5'
down_revision = 'a871c7986cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_games',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('game_title', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playoff_teams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'teams', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('playoff_games')
    # ### end Alembic commands ###
